name: "meus-recibos"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    command: tunnel run
    env_file:
      - ".env"
  api:
    image: ghcr.io/holerite/meusrecibos-api:release
    restart: always
    env_file:
      - ".env"
    deploy:
      mode: replicated
      replicas: 3
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
