name: "meus-recibos"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: cloudflare-tunnel
    restart: always
    command: tunnel run
    env_file:
      - ".env"
  api:
    image: ewr.vultrcr.com/meusrecibosapi/api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    env_file:
      - ".env"
    deploy:
      mode: replicated
      replicas: 3
  nginx:
    container_name: nginx
    image: nginx:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
