# fly.toml app configuration file generated for meusrecibos-api on 2024-11-16T09:55:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meusrecibos-api'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
