# fly.toml app configuration file generated for meusrecibos-api-dev on 2025-07-30T09:34:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meusrecibos-api-dev'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1
